CORTX-30131: Automated RADOS CI/CD - PART1 (IO Sanity).
Seagate/cortx-re pull request #1026
Opened 2022-05-19 09:01 UTC by nitisdev

Signed-off-by: Nitish Singh <nitish.singh@seagate.com>

# Problem Statement
- Automated IO Sanity and versioning.

# Design
-  IO Sanity

# Coding
   Checklist for Author
-  [x] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- End to end deployment:

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [x] Interface change (if any) are documented
- [x] Side effects on other features (deployment/upgrade)
- [x] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [x] JIRA number/GitHub Issue added to PR
- [x] PR is self reviewed
- [x] Jira and state/status is updated and JIRA is updated with PR link
- [x] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [x] Changes done to WIKI / Confluence page / Quick Start Guide

2022-05-25 11:21 UTC, gauravchaudhari02 approved these changes

2022-05-26 04:52 UTC, shailesh-vaidya requested changes

2022-05-26 04:52 UTC, shailesh-vaidya commented on solutions/kubernetes/ceph-binary-build.sh
> +mount="cortx-storage.colo.seagate.com:/mnt/data1/releases/ceph"
Can we make this as input parameter

2022-05-26 04:52 UTC, shailesh-vaidya commented on solutions/kubernetes/ceph-deploy.sh
> +CEPH_DEPLOYMENT="True"
Please change `True` to `true`

2022-05-26 05:16 UTC, nitisdev commented on solutions/kubernetes/ceph-binary-build.sh
> +mount="cortx-storage.colo.seagate.com:/mnt/data1/releases/ceph"
Done

2022-05-26 05:16 UTC, nitisdev commented on solutions/kubernetes/ceph-deploy.sh
> +CEPH_DEPLOYMENT="True"
Done

2022-05-27 04:50 UTC, shailesh-vaidya submitted a review, later dismissed

2022-05-27 05:11 UTC, gauravchaudhari02 commented on jenkins/automation/rgw/ceph/ceph-build-docker.groovy
> +            choices: ['ubuntu-20.04', 'centos-8', 'rockylinux-8.4'],
lets keep `rockylinux-8.4` as default

2022-05-27 05:11 UTC, gauravchaudhari02 commented on jenkins/automation/rgw/ceph/ceph-build-vm.groovy
> +            choices: ['ubuntu-20.04', 'centos-8', 'rockylinux-8.4'],
lets keep `rockylinux-8.4` as default

2022-05-27 09:18 UTC, nitisdev commented on jenkins/automation/rgw/ceph/ceph-build-vm.groovy
> +            choices: ['ubuntu-20.04', 'centos-8', 'rockylinux-8.4'],
Done

2022-05-27 09:18 UTC, nitisdev commented on jenkins/automation/rgw/ceph/ceph-build-docker.groovy
> +            choices: ['ubuntu-20.04', 'centos-8', 'rockylinux-8.4'],
Done

2022-05-27 12:39 UTC, gauravchaudhari02 approved these changes

2022-05-30 06:27 UTC, shailesh-vaidya approved these changes

2022-05-30 06:27 UTC, merged