CORTX-31845: Fix Codacy Badge
Seagate/cortx-re pull request #1083
Opened 2022-06-21 06:56 UTC by mukul-seagate11

Signed-off-by: Mukul Malhotra <mukul.malhotra@seagate.com>

# Problem Statement
- Fix Codacy Badge

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [x] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM
- [ ] Jenkins pipelines used for testing

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [x] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [x] JIRA number/GitHub Issue added to PR
- [x] PR is self reviewed
- [x] Jira and state/status is updated and JIRA is updated with PR link
- [x] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [x] Changes done to WIKI / Confluence page / Quick Start Guide

2022-06-22 04:43 UTC, shailesh-vaidya requested changes
Codacy badge changes looks good. Seems the license badge is removed. Please add it back.

2022-06-23 05:52 UTC, mukul-seagate11 commented
> Codacy badge changes looks good. Seems the license badge is removed. Please add it back.

@shailesh-vaidya, License badge has been re-added

2022-06-23 06:10 UTC, shailesh-vaidya approved these changes

2022-06-24 07:54 UTC, gauravchaudhari02 approved these changes

2022-06-24 08:21 UTC, merged