CORTX-34384: Change to test Whitesource config parameters
Seagate/cortx-re pull request #1268
Opened 2022-12-08 09:08 UTC by pankajgborole

# Problem Statement
There is request from PSO team to modify few parameters on Mend side to enable policy checks and license violations
In .whitesource file we need to set enableLicenseViolations=true
If file whitesource.config exists then we need to update checkPolicies=true if not exists then we need to create file with this parameter

# Design
CORTX-34384

# Coding
   Checklist for Author
-  [x] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM
- [] Jenkins pipelines used for testing

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [x] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [x] Jira ID/ COMMUNITY is prefixed in PR title
      Prefix Syntax - 
        `CORTX-<5 digit JIRA ID>: <PR Title>` - for Seagate Employees
        `COMMUNITY: <PR Title>`  - for open source contributors
- [x] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

2022-12-08 15:59 UTC, shailesh-vaidya requested changes

2022-12-08 15:59 UTC, shailesh-vaidya commented on .whitesource
> +  "configExternalURL": "",
Please check the alignment for entries.

2022-12-09 09:38 UTC, shailesh-vaidya submitted a review, later dismissed

2022-12-09 10:18 UTC, shailesh-vaidya approved these changes

2022-12-09 10:38 UTC, gauravchaudhari02 approved these changes

2022-12-12 04:23 UTC, merged