EOS:27373 - Added quickfix for busybox.
Seagate/cortx-re pull request #820
Opened 2022-01-19 05:17 UTC by nitisdev

Signed-off-by: Nitish Singh <nitish.singh@seagate.com>

# Problem Statement
- Added quickfix for busybox.

# Design
-  Added quickfix for busybox.

# Coding
   Checklist for Author
-  [x] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- Fresh VMs single node:
- Fresh VMs 3 node:

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [x] Interface change (if any) are documented
- [x] Side effects on other features (deployment/upgrade)
- [x] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [x] JIRA number/GitHub Issue added to PR
- [x] PR is self reviewed
- [x] Jira and state/status is updated and JIRA is updated with PR link
- [x] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

2022-01-19 06:15 UTC, gauravchaudhari02 submitted a review, later dismissed

2022-01-19 08:21 UTC, shailesh-vaidya requested changes
@nitisdev - Can you point me to the change for pulling busybox image.

2022-01-19 08:21 UTC, shailesh-vaidya commented on solutions/kubernetes/cortx-deploy-functions.sh
>  echo "---------------------------------------[ Setting up Master Node $HOSTNAME ]--------------------------------------"
Please change Master to Primary

2022-01-19 08:28 UTC, nitisdev commented
> @nitisdev - Can you point me to the change for pulling busybox image.

Removed local-path-provisioner deployment from k8s setup step. Now its deployment only with CORTX.

2022-01-19 08:42 UTC, nitisdev commented on solutions/kubernetes/cortx-deploy-functions.sh
>  echo "---------------------------------------[ Setting up Master Node $HOSTNAME ]--------------------------------------"
Done

2022-01-19 09:42 UTC, gauravchaudhari02 submitted a review, later dismissed

2022-01-19 10:24 UTC, nitisdev commented
> @nitisdev - Can you point me to the change for pulling busybox image.

Hence, no need to pull busybox explicitly now.

2022-01-19 13:50 UTC, shailesh-vaidya requested changes

2022-01-19 13:50 UTC, shailesh-vaidya commented on solutions/kubernetes/cortx-deploy.sh
> +       echo "PRIMARY NODE:" $PRIMARYPRIMARY_NODE
Should this bs only `$PRIMARY_NODE`

2022-01-19 14:11 UTC, nitisdev commented on solutions/kubernetes/cortx-deploy.sh
> +       echo "PRIMARY NODE:" $PRIMARYPRIMARY_NODE
Done

2022-01-20 11:29 UTC, gauravchaudhari02 approved these changes

2022-01-20 12:19 UTC, shailesh-vaidya approved these changes

2022-01-20 12:19 UTC, merged