CORTX-28910 : granular image optimization
Seagate/cortx-re pull request #901
Opened 2022-03-07 08:41 UTC by gauravchaudhari02

# Problem Statement
- Reduce and optimize redundant codebase of granular image creation process

# Design
-  Maintain single requirements files for all components.

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

2022-03-07 16:34 UTC, shailesh-vaidya requested changes
Can you please test deployment and IO operations with images generated from this PR codebase?
Need to update - https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/377226174/How+to+request+Third+party+package+addition+removal

2022-03-21 19:25 UTC, gauravchaudhari02 commented on docker/cortx-deploy/python_requirements.txt
> +setuptools==36.0.1 #cortx-ha
Done

2022-03-21 19:25 UTC, gauravchaudhari02 commented on docker/cortx-deploy/Dockerfile
> +RUN if [[ $OS_TYPE =~ "centos" ]]; then yum-config-manager --disable base,extras,updates; fi
Done

2022-03-29 04:52 UTC, shailesh-vaidya commented
@gauravchaudhari02 When can we plan to merge this PR?

2022-05-16 08:44 UTC, shailesh-vaidya reviewed
Looks good. Please once validate only the image generation part of the community - Refer - https://github.com/Seagate/cortx/blob/main/doc/community-build/docker/cortx-all/README.md 
Please confirm that all latest third-party package changes are accommodated - https://github.com/Seagate/cortx-re/pulls?q=is%3Apr+is%3Aclosed+label%3Acortx-third-party

2022-05-18 04:31 UTC, merged