CORTX-31001: Non Jenkins RE Deployment steps to be modified for community-CORTX-Deployment
Seagate/cortx-re pull request #992
Opened 2022-05-04 09:57 UTC by swatid-seagate

Signed-off-by: Swatid <swati.dhotarkar@seagate.com>

# Problem Statement
-Non Jenkins RE Deployment steps to be modified for community-CORTX-Deployment
https://jts.seagate.com/browse/CORTX-31001

# Review Checklist 
  Checklist for Author
- [Done ] JIRA number/GitHub Issue added to PR
- [ Done] Jira and state/status is updated and JIRA is updated with PR link
- [Done ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to [solutions/community-deploy/CORTX-Deployment.md](https://github.com/swatid-seagate/cortx-re/blob/cortx-deployment-update/solutions/community-deploy/CORTX-Deployment.md)

-----
[View rendered solutions/community-deploy/CORTX-Deployment.md](https://github.com/swatid-seagate/cortx-re/blob/cortx-deployment-update/solutions/community-deploy/CORTX-Deployment.md)

2022-05-04 10:18 UTC, shailesh-vaidya requested changes

2022-05-04 10:18 UTC, shailesh-vaidya commented on solutions/community-deploy/CORTX-Deployment.md
> +### Types of configurations available for `solution.yaml` file
This is not a prerequisite. This should go into a separate section in Deploy the Cortx Stack on K8s Cluster

2022-05-04 10:18 UTC, shailesh-vaidya commented on solutions/community-deploy/CORTX-Deployment.md
> +ls /dev/sd*
Please paste the exact command output for better understanding. e.g. 
```
[root@test ~]# ls /dev/sd*
/dev/sda  /dev/sda1  /dev/sda2  /dev/sdb  /dev/sdc  /dev/sdd  /dev/sde  /dev/sdf  /dev/sdg  /dev/sdh  /dev/sdi
[root@test ~]#
```

2022-05-04 10:18 UTC, shailesh-vaidya commented on solutions/community-deploy/CORTX-Deployment.md
>   2. You also deploy CORTX on AWS EC2 instance. Please follow [CORTX Deployment on AWS](https://github.com/Seagate/cortx-re/blob/main/solutions/community-deploy/cloud/AWS/README.md)
You also deploy CORTX on AWS EC2 instance
should be
You can deploy CORTX on AWS EC2 instance also.

2022-05-04 10:18 UTC, shailesh-vaidya commented on solutions/community-deploy/CORTX-Deployment.md
> +git clone https://github.com/Seagate/cortx-re
Use  `git clone https://github.com/Seagate/cortx-re && cd $PWD/cortx-re/solutions/kubernetes`

2022-05-04 10:18 UTC, shailesh-vaidya commented on solutions/community-deploy/CORTX-Deployment.md
> +To create the host file and change the root user password, run the following command
Please mention that change `rootuserpassword` with your system password.

2022-05-04 10:18 UTC, shailesh-vaidya commented on solutions/community-deploy/CORTX-Deployment.md
> +If you want to run pods on to the master node as well, give first input parameter for `cluster-setup.sh` script as true else false.
You do not need to mention `false` explicitly.

2022-05-04 10:18 UTC, shailesh-vaidya commented on solutions/community-deploy/CORTX-Deployment.md
> +## Deploy the Cortx Stack on K8s Cluster
s/Cortx/CORTX

2022-05-04 10:18 UTC, shailesh-vaidya commented on solutions/community-deploy/CORTX-Deployment.md
> +   1. CORTX_SCRIPTS_BRANCH : If you want to use another cortx-K8s branch then export this variable with your branch (Default value CORTX_SCRIPTS_BRANCH="v0.2.1").
Maybe we should mention the default values of all the parameters also. We can use below format,
Variable Name |  Default value | description

2022-05-04 10:18 UTC, shailesh-vaidya commented on solutions/community-deploy/CORTX-Deployment.md
> +   - Manual means we need to create solution.yaml file and replace it at script location. If you wanted to create solution yaml manually, then create it and place it at script location and configure
Maybe we need to rephrase this better 
Automated - solution.yaml is created by script if VM is created as per standard specification.
Manual - User needs to create solution.yaml with required disks. image details etc.

2022-05-05 04:59 UTC, shailesh-vaidya requested changes

2022-05-05 04:59 UTC, shailesh-vaidya commented on solutions/community-deploy/CORTX-Deployment.md
> +If you want to run pods on to the master node as well, pass the first input parameter for `cluster-setup.sh` script as true.
s/master/primary/

2022-05-05 04:59 UTC, shailesh-vaidya commented on solutions/community-deploy/CORTX-Deployment.md
> +If you want to run pods on to the master node as well, pass the first input parameter for `cluster-setup.sh` script as true.
Can we make this bulleted list or make it single line

2022-05-05 04:59 UTC, shailesh-vaidya commented on solutions/community-deploy/CORTX-Deployment.md
> +   -  Automated - solution.yaml is created by script if VM is created as per standard specification.
Please use SOLUTION_CONFIG_TYPE variable and use the same format as above.

2022-05-05 08:32 UTC, shailesh-vaidya commented on solutions/community-deploy/CORTX-Deployment.md
> +### Types of configurations available for `solution.yaml` file
@swatid-seagate Could you please address this.

2022-05-05 08:35 UTC, shailesh-vaidya commented on solutions/community-deploy/CORTX-Deployment.md
> +If you want to run pods on to the master node as well, pass the first input parameter for `cluster-setup.sh` script as true.
Please remove word `master`

2022-05-05 08:37 UTC, shailesh-vaidya requested changes
Please update PR title and fill PR template details.

2022-05-05 08:37 UTC, shailesh-vaidya commented on solutions/community-deploy/CORTX-Deployment.md
> +## Deploy the CORTX Stack on K8s Cluster
We have the heading `Deploy the CORTX Stack on K8s cluster` at the top. So this should be only `Deploy CORTX Stack`

2022-05-05 12:53 UTC, shailesh-vaidya submitted a review, later dismissed
Approved. Please fix Codacy check

2022-05-05 13:33 UTC, gauravchaudhari02 commented on solutions/community-deploy/CORTX-Deployment.md
> +   1. CORTX_SCRIPTS_BRANCH | CORTX_SCRIPTS_BRANCH="v0.2.1" : If you want to use another cortx-K8s branch then export this variable with your branch.
Can we add parameters in table format? refer below as an example.
https://github.com/marketplace/actions/action-git-diff-suggestions#inputs

2022-05-06 13:42 UTC, shailesh-vaidya approved these changes

2022-05-09 05:45 UTC, gauravchaudhari02 approved these changes

2022-05-09 10:49 UTC, merged