Updated README.md for formatting
Seagate/cortx-re pull request #994
Opened 2022-05-04 12:54 UTC by swatid-seagate

Updated README.md for formatting. The file describes steps to install and deploy cortx on AWS.

Signed-off-by: Swatid <swati.dhotarkar@seagate.com>

# Problem Statement
- Problem statement

# Design
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

2022-05-05 04:54 UTC, shailesh-vaidya requested changes

2022-05-05 04:54 UTC, shailesh-vaidya commented on solutions/community-deploy/cloud/AWS/README.md
> +os_version          = "CentOS 7.8.2003 x86_64"
Please use `CentOS 7.9.2009 x86_64`

2022-05-05 04:54 UTC, shailesh-vaidya commented on solutions/community-deploy/cloud/AWS/README.md
> +We will use [cortx-build](https://github.com/Seagate/cortx/pkgs/container/cortx-build) docker image to compile entire CORTX stack.
Can we make this bulleted list

2022-05-05 04:54 UTC, shailesh-vaidya commented on solutions/community-deploy/cloud/AWS/README.md
> +After CORTX build is ready, follow [CORTX Deployment](https://github.com/Seagate/cortx-k8s/blob/main/doc/cortx-aws-k8s-installation.md) to deploy CORTX on AWS instance.
Can we make this bulleted list

2022-05-05 04:54 UTC, shailesh-vaidya commented on solutions/community-deploy/cloud/AWS/README.md
> +Clone the `cortx-re` repository and change the directory to `cortx-re/solutions/community-deploy/cloud/AWS`.
Can we make this bulleted list

2022-05-05 08:29 UTC, shailesh-vaidya reviewed
LGTM 
@swatid-seagate Please update the PR title to reflect the actual problem statement and add a Jira ticket at the start. Please fill PR template details.

2022-05-05 12:55 UTC, shailesh-vaidya approved these changes
Please fix DCO check

2022-05-06 09:58 UTC, gauravchaudhari02 approved these changes

2022-05-06 13:43 UTC, shailesh-vaidya submitted a review, later dismissed

2022-05-09 06:57 UTC, mukul-seagate11 requested changes

2022-05-09 06:57 UTC, mukul-seagate11 commented on solutions/community-deploy/cloud/AWS/README.md
> +# ./tool_setup.sh
remove '#' from the commands

2022-05-09 07:12 UTC, gauravchaudhari02 commented on solutions/community-deploy/cloud/AWS/README.md
> +- Execute Terraform code (as shown in above section) to create AWS instance for CORTX Build and Deployment.
it should be `below section` instead of `above section` right?

2022-05-09 07:17 UTC, mukul-seagate11 requested changes

2022-05-09 07:17 UTC, mukul-seagate11 commented on solutions/community-deploy/cloud/AWS/README.md
> +# curl ipinfo.io/ip
remove '#' from the commands

2022-05-09 07:17 UTC, mukul-seagate11 commented on solutions/community-deploy/cloud/AWS/README.md
> +# ssh -i cortx.pem centos@"<AWS instance public-ip>" sudo bash /home/centos/setup.sh
remove '#' from the commands

2022-05-09 07:17 UTC, mukul-seagate11 commented on solutions/community-deploy/cloud/AWS/README.md
> +# sudo su -
remove '#' from the commands

2022-05-09 07:17 UTC, mukul-seagate11 commented on solutions/community-deploy/cloud/AWS/README.md
> +# terraform validate && terraform destroy -var-file user.tfvars --auto-approve
remove '#' from the commands

2022-05-09 09:07 UTC, mukul-seagate11 approved these changes
looks good

2022-05-09 09:12 UTC, mukul-seagate11 commented
DCO is ignored as an exception due to commit is not getting signed-off

2022-05-09 09:49 UTC, merged